#!/usr/bin/python


# iso.3.6.1.4.1.45.1.6.3.3.1.1.10.6.10.0 = INTEGER: 5
# iso.3.6.1.4.1.45.1.6.3.3.1.1.10.6.11.0 = INTEGER: 5
# iso.3.6.1.4.1.45.1.6.3.3.1.1.10.6.12.0 = INTEGER: 5
# iso.3.6.1.4.1.45.1.6.3.3.1.1.10.6.13.0 = INTEGER: 5



# The fans start at id 10 through 14. re-counting them here.
# I hope it doesn't fail on other bigger compatible ones.
def parse_avaya_ers45k_fans(info):
    faninfo = []
    for state, fanid in info:
        fanid = int(float(fanid)) - 9
        faninfo += [ (fanid, state) ]
    return faninfo


def inventory_avaya_ers45k_fans(info):
    inventory = []
    faninfo = parse_avaya_ers45k_fans(info)
    for fanid, state in faninfo:
        inventory += [ ( fanid, None ) ]
    return inventory


def check_avaya_ers45k_fans(item, _no_params, info):
    faninfo = parse_avaya_ers45k_fans(info)
    
    for fanid, state in faninfo:
        if fanid != item:
            continue
        if state == "5":
           return 0, "Fan reports state: normal"
        elif state == "3":
           return 2, "Fan reports state: failure"
    else:
        return 3, "Fan not found"


check_info["avaya_ers45k_fans"] = {
    "check_function"        : check_avaya_ers45k_fans,
    "inventory_function"    : inventory_avaya_ers45k_fans,
    "service_description"   : "Fan %s",
    "snmp_info"             : ('.1.3.6.1.4.1.45.1.6.3.3.1.1.10.6', [ '', OID_END ]),
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.45.3.71.1"),
    "has_perfdata"          : False,
}

