#!/usr/bin/python

#Output
#<<<freebsd_updates>>>
#release: 9.1-RELEASE-p3
#security:       27

target_releases = [ 
  "9.1-RELEASE-p12", 
  "8.3-RELEASE-p16", 
  "9.2-RELEASE", 
]

def inventory_freebsd_updates(info):
    return [ (None, None) ]


def check_freebsd_updates(_no_item, _no_params, info):

    msg = ""

    for line in info:
        key, val = line
        if   key == "release:":
           osver = val
           osmsg   = "system is running %s" % val
           if val not in target_releases:
               state = 2
               osmsg = osmsg + "(!!)"
           else:
               state = 0

        if key == "security:":
           patches = int(val)

    if  patches > 0:
       state = max(state, 2)
       patchmsg = "%s security updates for ports(!!)" % patches
    else:
       state = max(state, 0)
       patchmsg = "no security updates for ports"

    # Bug: the comma doesn't show.
    msg = osmsg + ", " + patchmsg
    
    return state, msg


check_info["freebsd_updates"] = {
    "check_function"      : check_freebsd_updates,
    "inventory_function"  : inventory_freebsd_updates,
    "service_description" : "FreeBSD Updates",
    "has_perfdata"        : "false",
}
