#!/bin/sh
# check release and portaudit status, the check needs both to be installed.


get_info()
{
    version=`uname -r`

    # portaudit _can_ be very slow, it seems to take 5x longer on vmware ;)
    # if it becomes a problem for you:
    # check on the age of /var/db/portaudit/auditfile.tbz and the installed
    # package index (don't know where it is)

    portsec=`portaudit | grep "^Affected" | sort -u  | wc -l`
    echo "release: $version
    security: $portsec"
}


if which portaudit > /dev/null 2>&1; then
    echo '<<<freebsd_updates>>>'
    get_info
fi
