#!/bin/sh
# 
# This agent plugin for Check_MK / Nagios is supposed to read data provided by the linux EDAC driver
# Right now, the driver can read status of memory modules and pci busses and we'll try to monitor that.

# The best stop for alll things EDAC is http://buttersideup.com/edacwiki/ and the edac.txt in the kernel doc.


if [ -d /sys/devices/system/edac/mc ]; then
    # EDAC memory driver running
    echo '<<<edac.mem>>>'
    # Iterate all memory controllers, print memory info and EDAC mode. Maybe later add DIMM label support.
    for mc in /sys/devices/system/edac/mc/* ; do 
        for csrow in $mc/csrow* ; do 
            echo "$csrow $(cat $csrow/{size_mb,mem_type,ce_count,ue_count,edac_mode} | tr '\n' ' ')" 
        done
    done
fi

test -d /sys/devices/system/edac/pci &&
if [ `cat /sys/devices/system/edac/pci/check_pci_errors` = 1 ]; then
    # By default, Linux does ignore PCI crc/ecc. Only do checks if the admin enabled it.
    echo '<<<edac.pci>>>'


fi
