#!/bin/bash


megaraid_info()
{

    PDINFO=$(MegaCli -PDlist -a0)

    echo "$PDINFO" | \
    while read line ; do
        case "$line" in
           # FIRST LINE
           "Enclosure Device ID"*) #Enclosure Device ID: 252
            ENC=$( echo "$line" | awk '{print $4}')
                  unset SLOT LOG_DEV_ID VEND MODEL
        ;;
        "Slot Number"*)  #Slot Number: 7
            SLOT=$( echo "$line" | awk '{print $3}')
        ;;
        "Device Id"*)    #Device Id: 19
            LOG_DEV_ID=$( echo "$line" | awk '{print $3}')
        ;;
        "PD Type"*)      #PD Type: SATA
            VEND=$( echo "$line" | awk '{print $3}')
        ;;
        # This is the last value, generate output here 
        "Inquiry Data"*)
         #Inquiry Data: WD-WCC1T1035197WDC WD20EZRX-00DC0B0 80.00A80
            # $4 seems to be better for some vendors... wont be possible to get this right.
            MODEL=$( echo "$line" | awk '{print $3}')

            # /dev/sdc ATA SAMSUNG_SSD_830   5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       - 
            smartctl -d megaraid,${LOG_DEV_ID} -v 9,raw48 -A /dev/sg0 | \
              grep Always  | egrep -v '^190(.*)Temperature(.*)'       | \
              sed "s|^|Enc${ENC}/Slot${SLOT} $VEND $MODEL |" 
            ;;
            esac

       done
}
       

# Only handle always updated values, add device path and vendor/model
if which smartctl > /dev/null 2>&1 ; then
    echo '<<<smart>>>'
    for D in /dev/[sh]d[a-z] /dev/[sh]d[a-z][a-z]; do
        N=${D##*/}
        if [ -r /sys/block/$N/device/vendor ]; then
            VEND=$(tr -d ' ' < /sys/block/$N/device/vendor)
        else
            # 2012-01-25 Stefan Kaerst CDJ - in case $N does not exist
            VEND=ATA
        fi
        # 2012-01-25 Stefan Kaerst CDJ - special option in case vendor is AMCC
        if [ "$VEND" == "AMCC" ]; then
            D='/dev/twa0'
            SPECOPS='-d 3ware,0'
        fi
        if [ -r /sys/block/$N/device/model ]; then
            MODEL=$(sed -e 's/ /_/g' -e 's/_*$//g' < /sys/block/$N/device/model)
        else
            MODEL=$(smartctl -a $D | grep -i "device model" | sed -e "s/.*:[ ]*//g" -e "s/\ /_/g")
        fi
        if [ "$MODEL" = "iSCSI_Disk" ]; then
            continue
        fi
        smartctl $SPECOPS -v 9,raw48 -A $D | grep Always  | egrep -v '^190(.*)Temperature(.*)' | sed "s|^|$D $VEND $MODEL |"
    done 2>/dev/null


    # Call MegaRaid submodule if conditions are met
    if which MegaCli > /dev/null && [ -c /dev/sg0 ] ; then 
        megaraid_info
    fi
   

fi
