#!/usr/bin/python



# A check for hardware stuff on Areca raid controllers.

# Voltages and battery
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.1 = INTEGER: 1
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.2 = INTEGER: 2
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.3 = INTEGER: 3
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.4 = INTEGER: 4
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.5 = INTEGER: 5
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.6 = INTEGER: 6
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.7 = INTEGER: 7
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.8 = INTEGER: 8
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.1.9 = INTEGER: 9
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.1 = STRING: "12V"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.2 = STRING: "5V"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.3 = STRING: "3.3V"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.4 = STRING: "DDR-II +1.8V"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.5 = STRING: "PCI-E  +1.8V"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.6 = STRING: "CPU    +1.8V"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.7 = STRING: "CPU    +1.2V"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.8 = STRING: "DDR-II +0.9V"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.2.9 = STRING: "Battery Status"
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.1 = INTEGER: 11977
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.2 = INTEGER: 5026
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.3 = INTEGER: 3296
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.4 = INTEGER: 1808
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.5 = INTEGER: 1808
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.6 = INTEGER: 1824
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.7 = INTEGER: 1184
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.8 = INTEGER: 896
#.1.3.6.1.4.1.18928.1.2.2.1.8.1.3.9 = INTEGER: 255

#snmp_info   : oid(".1.3.6.1.4.1.18928.1.2.2.1.8.1"), [ "1", "2", "3" ]

# Turn this into something much sweeter.
# The battery status doesnt really belong in here.
#{'voltages': {'12V': 11977,
#              'Battery Status': 255,
#              '5V': 5053,
#              'PCI-E  +1.8V': 1808}}

def parse_areca(info, what):
    areca_info = {}
    areca_info[what] = {}
    for line in info[0]:
        if len(line) == 3:
            id, sensor_name, value = line
            areca_info[what][sensor_name] = saveint(value)
            

def inventory_areca_hba_voltages(info):
    inventory = []

    # The next part isnt getting passed back properly, 
    # so we break it here.
    return inventory
    areca_info = parse_areca(info, "voltages")
    print areca_info
    for sensor_name in areca_info["voltages"].keys():
        if sensor_name.lower() != "battery status":
            inventory.append((sensor_name, None))
    
    return  inventory


def check_areca_hba_voltages(item, _no_params, info):
    return (3, "UNKNOWN - check not yet implemented")

#            perfdata = [ ( item, temp, warn, crit, 0 ) ]
#            return (state, nagios_state_names[state] + " - Temperature is %dC" % temp, perfdata)
    
#    return (3, "UNKNOWN - sensor not found in agent output")


check_info["areca_hba_voltages"]  = {
    "check_function"      : check_areca_hba_voltages,
    "inventory_function"  : inventory_areca_hba_voltages,
    "has_perfdata"        : True,
    "service_description" : "Temperature %s",
    # Find Areca SAS MIB
    "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.18928.1"),
    "snmp_info"           : [(".1.3.6.1.4.1.18928.1.2.2.1.8.1", [ "1", "2", "3" ])],
}

