#!/bin/bash

#"${status} bacula-dir-connect - ${txt}"

type bconsole 2>&1 >/dev/null || exit 0

jobs=$(echo "status dir" | bconsole -n  | egrep -i '(is.*on|is.*for|running)')

if echo "$jobs"  | grep -i "no jobs running" > /dev/null ; then
    echo "0 bacula-jobs - OK - no running jobs"
    exit 0
fi

    num_run=$( echo "$jobs" | grep -c "is running")
 num_mounts=$( echo "$jobs" | grep -c "waiting for a mount request" )
num_waiting=$( echo "$jobs" | grep -c waiting )

if [ $num_run = 0 ] && [ $num_waiting -ge 0 ]; then
    echo "2 bacula-jobs - CRIT - all jobs are waiting"
    exit 2
fi
# could add perfdata here, if you need it....

if [ $num_mounts -ge $num_run ]; then
    echo "2 bacula-jobs - CRIT - all running jobs are stuck on mounts"
    exit 2
fi


echo "0 bacula-jobs - OK - $num_run running jobs, $num_waiting waiting jobs"


