#!/usr/bin/perl

# Pipe in curl data
use XML::Simple;

my $in = <>;
my $parsed = XMLin($in, KeyAttr => ['id']);

print STDOUT "<<<allnet_sensors:sep(124)>>>\n";
while(my ($id, $stuff) = each %{$parsed->{'sensor'}}){
 print STDOUT join("|",
               "id", $id,
               "unit", $stuff->{unit},
               "name", $stuff->{name},
               "current", $stuff->{current}) . "\n";
}
