#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def agent_pjlink_arguments(params, hostname, ipaddress):
    args = []

    args += [ ipaddress ] 

    return args

special_agent_info['pjlink'] = agent_pjlink_arguments
