#!/bin/sh
#
# cmkstatus -  
# A script that can query the cmk status of the host you're currently messing
# with. 
# This little admin helper exits with return code 0 if there's no errors
# on the host. It can be instructed to output total and errors.
# It should be able to trigger a recheck
# 
# Author - Florian Heigl <fh@mathias-kettner.de>

# Step 1: 
# Configure the script via the below config file
if [ -r /etc/check_mk/cmkstatus.conf ]; then 
    . /etc/check_mk/cmkstatus.conf
else 
# otherwise it will fall back to my test settings.
    NAGIOSSERVER=192.168.10.135
    SITENAME=wartungsfenster
fi

# Step 2:
# Set up SSH command restricted access for your host.
# You need to generate a ssh key just for this purpose ( see id_dsa below )
# You need to add the public key to the authorized_keys file for your nagios
# user.
# Minimum example - need to add options like no-pty
# command=". ~/.profile ; check_mk --cache -v dtc.wartungsfenster.de" ssh-dss AAAA[...snip...]
# 


#STATUS=$(ssh -i /root/.ssh/id_dsa_cmk -nq -o PreferredAuthentications=PublicKey $SITENAME@${NAGIOSSERVER} 2>&1 | grep -v version)
STATUS=$(ssh -i ~/.ssh/id_dsa -nq $SITENAME@${NAGIOSSERVER} 2>&1 | grep -v version)

TOTAL=$(echo "$STATUS" | wc -l)
#OK=$(echo "$STATUS"   | grep -c OK)
NONOK=$(echo "$STATUS" | grep -v -e OK -e "Counter wrapped")
NUMERR=$(echo "$NONOK" | wc -l)

if [ ${NUMERR} = 0 ]; then
    # silenty exit
    exit 0 
fi

if [ "Xtotal" = "X${1}" ]; then
    # this only works if we got errors. 
    echo "(${NUMERR}/${TOTAL}) ERR/TOTAL"
fi 

if [ "Xshow" = "X${1}" ]  && [ $NUMERR -ge 1 ]; then
     echo "$NONOK" | cut -f1 -d\- 
fi 
exit 1


# thats it.
