#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# +------------------------------------------------------------------+
#
# This file is an addon for Check_MK.
# The official homepage for this check is at http://bitbucket.org/darkfader
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def inventory_areca_hba_raidsets(info):
    inventory = []

    # not sure why i end up with my info double stacked
    # but i'm sure it's me.
    for line in info[0]:
        if len(line) == 5:
            rs_id, rs_name, rs_state, rs_mem_sz, rs_mem_names = line
            inventory.append((rs_id, None))
    return inventory

def check_areca_hba_raidsets(item, _no_params, info):
    for line in info[0]:
        rs_id, rs_name, rs_state, rs_mem_sz, rs_mem_names = line

        if rs_id == item:
            if   rs_state == "Normal":
                state = 0
            elif rs_state == "Rebuilding":
                state = 1
            # I hope Offline is correct.
            elif rs_state in [ "Degraded", "Offline" ]:
                state = 2
            # Any state we don't know.
            else:
                state = 3

            msg = "%s is %s. (members: %s)" % (rs_name, rs_state, rs_mem_names)
            return (state, msg)
        
    return (3, "UNKW - Raidset not found in agent output")


check_info["areca_hba_raidsets"]  = {
    "check_function"      : check_areca_hba_raidsets,
    "inventory_function"  : inventory_areca_hba_raidsets,
    "has_perfdata"        : False,
    "service_description" : "Raid set %s",
    # Find Areca SAS MIB
    "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.18928.1"),
    "snmp_info"           : [(".1.3.6.1.4.1.18928.1.2.4.1.1", 
        # Below each enclosure there's the following structure for disk data
                                  [  #"2", "4" 
          "1", # Raidset id
          "2", # Raidset name
          "4", # Raidset State
          "7", # Member disk size
          "8", # Member disk names and states
                                  ]
                            )],
}

