#!/usr/bin/python

# FIXME: utf-8 encode


# hddEnclosure01Slots:
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.1.1 = 1
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.1.20 = 20
# hddEnclosure01Desc:
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.2.1 = "SLOT 01"
# hddEnclosure01Name:
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.3.20 = "WDC WD30EFRX-68AX9N0                    "
# hddEnclosure01Serial:
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.4.20 = "1234567            "
# hddEnclosure01FirmVer:
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.5.20 = "CC1H    "
# hddEnclosure01Capacity:
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.6.1 = 0
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.6.20 = 3000600
# hddEnclosure01Type:
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.7.1 = 0
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.7.20 = 1
#  hddEnclosure01State:
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.8.1 = "Empty Slot"
#.1.3.6.1.4.1.18928.1.2.3.2.4.1.8.20 = "RaidSet Member"

# How to grok:
#.1.3.6.1.4.1.18928.1.2.3.E.4.1.F.D
#                         |     | |
#                         |     | +---enc disk id
#                         |     +-----field
#                         +-------enclosure


import pprint

def inventory_areca_hba_pdisks(info):
    inventory = []
    for line in info:
        for enclosure_slot in line:
            if len(enclosure_slot) == 8 and enclosure_slot[-1].split()[0] != "Empty":
                enc, slot = enclosure_slot[0].split(".")
                diskname = ("%d/%02d" % (int(enc), int(slot)))
                inventory.append((diskname, None))
    return inventory


check_info["areca_hba_pdisks"]  = {
#    "check_function"      : check_areca_hba_pdisks,
    "inventory_function"  : inventory_areca_hba_pdisks,
    "has_perfdata"        : True,
    "service_description" : "PDisk Enc/Sl %s",
    # Find Areca SAS MIB
    "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.18928.1"),
    "snmp_info"           : [(".1.3.6.1.4.1.18928.1.2.3", 
        # unclear: how does it look in jbod mode?
        # where does i get pony?
        # There's up to 8 enclosures, "1" is hardcoded having 8 slots.
        # probably it's the ext. SAS connector. 
                                  [ "1", "2", "3", "4", "5", "6", "7", "8" ], 
        # Below each enclosure there's the following structure for disk data
                                  [ "4.1.1", # The slot ids
                                    "4.1.2", # The slot descrs
                                    "4.1.3", # The disk model
                                    "4.1.4", # The disk fw
                                    "4.1.5", # The disk size
                       # The MIB seems wrong about the next ones
                                    "4.1.6", #
                                    "4.1.7", # 
                                    "4.1.8", #
                                  ]
                            )],
}

