#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# +------------------------------------------------------------------+
# 
# This file is an addon for Check_MK.
# The official homepage for this check is at http://bitbucket.org/darkfader
# 
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.1 = STRING: "12V"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.2 = STRING: "5V"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.3 = STRING: "3.3V"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.4 = STRING: "DDR-II +1.8V"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.5 = STRING: "PCI-E  +1.8V"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.6 = STRING: "CPU    +1.8V"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.7 = STRING: "CPU    +1.2V"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.8 = STRING: "DDR-II +0.9V"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.2.9 = STRING: "Battery Status"
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.1 = INTEGER: 11977
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.2 = INTEGER: 5026
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.3 = INTEGER: 3312
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.4 = INTEGER: 1824
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.5 = INTEGER: 1808
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.6 = INTEGER: 1824
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.7 = INTEGER: 1184
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.8 = INTEGER: 896
#iso.3.6.1.4.1.18928.1.2.2.1.8.1.3.9 = INTEGER: 255			# no battery
#iso.3.6.1.4.1.18928.1.2.2.1.9.1.1.1 = INTEGER: 1 			
#iso.3.6.1.4.1.18928.1.2.2.1.9.1.2.1 = STRING: "CPU Fan"
#iso.3.6.1.4.1.18928.1.2.2.1.9.1.3.1 = INTEGER: 0			# Missing
#iso.3.6.1.4.1.18928.1.2.2.1.10.1.1.1 = INTEGER: 1
#iso.3.6.1.4.1.18928.1.2.2.1.10.1.1.2 = INTEGER: 2
#iso.3.6.1.4.1.18928.1.2.2.1.10.1.2.1 = STRING: "CPU Temperature"
#iso.3.6.1.4.1.18928.1.2.2.1.10.1.2.2 = STRING: "Controller Temp."
#iso.3.6.1.4.1.18928.1.2.2.1.10.1.3.1 = INTEGER: 79
#iso.3.6.1.4.1.18928.1.2.2.1.10.1.3.2 = INTEGER: 34












snmp_info["areca_ctl_health"] = \
1.3.6.1.4.1.18928.1.2.2.1
     8,
     9,
    10,

.2 description
.3 value



snmp_scan_function["areca_ctl_health"] = \
    lambda oid ".1.3.6.1.4.1.18928.1.2" in ...
